apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-svc
  labels:
    service: udagram-feed-svc
spec:
  selector:
    app: udagram-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080